name: meeting_place_mediator

description: Mediator SDK is a package for securely connecting and authenticating with DIDComm mediators to send and receive messages, including out-of-band invitations.
repository: https://github.com/affinidi/affinidi-meetingplace-sdk-dart.git
version: 0.0.1-dev.7
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.0
  didcomm: ^2.0.3
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  mutex: ^3.1.0
  retry: ^3.1.2
  ssi: ^2.17.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  dart_flutter_team_lints: ^3.5.1
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.26.3
