name: meeting_place_core
description: The core Meeting Place package that implements Control Plane API and Mediator capabilities, including multi-identity management for enhanced privacy and anonymity.
version: 0.0.1-dev.12
repository: https://github.com/affinidi/affinidi-meetingplace-sdk-dart.git
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  crypto_keys_plus: ^0.5.0
  didcomm: ^2.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meeting_place_control_plane: ^0.0.1-dev.9
  meeting_place_mediator: ^0.0.1-dev.7
  meta: ^1.17.0
  mutex: ^3.1.0
  proxy_recrypt: ^1.1.3
  retry: ^3.1.2
  ssi: ^2.17.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  dio: ^5.9.0
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.26.2
