name: meeting_place_chat
description: Chat SDK is a package that provides secure, end-to-end encrypted messaging using Decentralised Identifiers (DID) and DIDComm v2.1 protocol.
version: 0.0.1-dev.24
repository: https://github.com/affinidi/affinidi-meetingplace-sdk-dart.git
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  didcomm: ^2.3.0
  json_annotation: ^4.9.0
  meeting_place_core: ^0.0.1-dev.23
  meta: ^1.17.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  ssi: ^2.17.1
  test: ^1.26.2
