name: meeting_place_drift_repository
description: The Meeting Place Drift Repository is a package that uses Drift to persist and manage channels, connection offers, groups, anc chat history in local device storage.
repository: https://github.com/affinidi/affinidi-meetingplace-sdk-dart.git
version: 0.0.1-dev.17
resolution: workspace

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  clock: ^1.1.2
  drift: ^2.28.1
  meeting_place_chat: ^0.0.1-dev.16
  meeting_place_core: ^0.0.1-dev.15
  path: ^1.9.1
  sqlite3: ^2.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.8
  dart_flutter_team_lints: ^3.5.1
  drift_dev: ^2.28.0
  test: ^1.25.6
