name: meeting_place_core_example
description: Meeting place core SDK examples.
version: 0.0.1-dev.0
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  meeting_place_core:
    path: ../../../packages/meeting_place_core
  pretty_json: ^2.0.0
  ssi: ^3.0.2
  uuid: ^4.5.1
