name: meeting_place_control_plane
description: An interface to the Control Plane API for publishing connection offers to establish a secure communication channel between participants in Meeting Place.
version: 0.0.1-dev.12
repository: https://github.com/affinidi/affinidi-meetingplace-sdk-dart.git
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  built_collection: ^5.1.1
  built_value: ">=8.4.0 <9.0.0"
  collection: ^1.19.1
  crypto: ^3.0.6
  didcomm: ^2.3.2
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  one_of: ">=1.5.0 <2.0.0"
  one_of_serializer: ">=1.5.0 <2.0.0"
  retry: ^3.1.2
  ssi: ^3.0.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.8
  built_value_generator: ">=8.4.0 <9.0.0"
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.26.2
