name: meeting_place_core_chat
description: Meeting place chat SDK examples.
version: 0.0.1-dev.0
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  meeting_place_chat: ^0.0.1-dev.9
  meeting_place_core: ^0.0.1-dev.9
  pretty_json: ^2.0.0
  ssi: ^2.12.4
  uuid: ^4.5.1
